title: Chris Baker
description: mail.chris.baker@gmail.com
google_analytics: UA-54784747-1
show_downloads: false
theme: jekyll-theme-slate

gems:
  - jekyll-mentions

github:
  is_project_page: false
